# Generated by Django 5.1.4 on 2025-01-13 13:33

import django.db.models.deletion
import django.utils.timezone
import luapol_app.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSection',
            fields=[
                ('id', models.CharField(default=luapol_app.models.generate_unique_key, editable=False, max_length=20, primary_key=True, serialize=False)),
                ('section_id', models.IntegerField()),
                ('block_number', models.IntegerField(unique=True)),
                ('block_description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Preguntas',
            fields=[
                ('id', models.CharField(default=luapol_app.models.generate_unique_key, max_length=20, primary_key=True, serialize=False)),
                ('id_pregunta', models.CharField(max_length=255)),
                ('n_pregunta', models.CharField(max_length=255)),
                ('pregunta', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='StudyTopic',
            fields=[
                ('id', models.CharField(default=luapol_app.models.generate_unique_key, editable=False, max_length=20, primary_key=True, serialize=False)),
                ('title_number', models.IntegerField(unique=True)),
                ('description', models.CharField(max_length=255)),
                ('page_count', models.IntegerField(default=0)),
                ('section_id', models.IntegerField()),
                ('section_description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ForoBase',
            fields=[
                ('id', models.CharField(default=luapol_app.models.generate_unique_key, editable=False, max_length=20, primary_key=True, serialize=False)),
                ('asunto', models.CharField(max_length=255)),
                ('contenido', models.TextField()),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('creado_por_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entrada de Foro',
                'verbose_name_plural': 'Entradas de Foro',
                'ordering': ['-likes', '-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ForoMensajes',
            fields=[
                ('id', models.CharField(default=luapol_app.models.generate_unique_key, editable=False, max_length=20, primary_key=True, serialize=False)),
                ('contenido', models.TextField(verbose_name='Contenido del Mensaje')),
                ('fecha_publicacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('autor_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor del Mensaje')),
                ('foro_base_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='luapol_app.forobase')),
            ],
            options={
                'verbose_name': 'Mensaje de Foro',
                'verbose_name_plural': 'Mensajes de Foro',
                'ordering': ['-likes', '-fecha_publicacion'],
            },
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.CharField(default=luapol_app.models.generate_unique_key, editable=False, max_length=20, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ForoPregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foro_base', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='foropregunta', to='luapol_app.forobase')),
                ('id_pregunta_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas_pregunta', to='luapol_app.preguntas', verbose_name='Pregunta Relacionada')),
            ],
            options={
                'verbose_name': 'Entrada de Foro (Pregunta)',
                'verbose_name_plural': 'Entradas de Foro (Preguntas)',
            },
        ),
        migrations.CreateModel(
            name='Respuestas',
            fields=[
                ('id', models.CharField(default=luapol_app.models.generate_unique_key, max_length=20, primary_key=True, serialize=False)),
                ('n_respuesta', models.CharField(max_length=255)),
                ('id_respuesta', models.CharField(max_length=255)),
                ('es_correcta', models.BooleanField(default=False)),
                ('descripcion', models.CharField(max_length=1000)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('pregunta_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='luapol_app.preguntas')),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoTest',
            fields=[
                ('id', models.CharField(default=luapol_app.models.generate_unique_key, editable=False, max_length=20, primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('es_correcta', models.BooleanField(default=False)),
                ('pregunta_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luapol_app.preguntas')),
                ('respuesta_elegida_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luapol_app.respuestas')),
            ],
        ),
        migrations.CreateModel(
            name='StudyAvailability',
            fields=[
                ('id', models.CharField(default=luapol_app.models.generate_unique_key, editable=False, max_length=20, primary_key=True, serialize=False)),
                ('study_mode', models.CharField(choices=[('tests', 'Solo Tests'), ('study', 'Estudio Completo')], default='study', max_length=20, verbose_name='Modo de estudio')),
                ('user_oto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PreguntasPorTema',
            fields=[
                ('id', models.CharField(default=luapol_app.models.generate_unique_key, editable=False, max_length=20, primary_key=True, serialize=False)),
                ('anio', models.IntegerField()),
                ('numero_preguntas', models.IntegerField()),
                ('tema_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luapol_app.studytopic')),
            ],
        ),
        migrations.CreateModel(
            name='ForoGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foro_base', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='forogeneral', to='luapol_app.forobase')),
                ('id_tema_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entradas_general', to='luapol_app.studytopic', verbose_name='Tema Relacionado')),
            ],
            options={
                'verbose_name': 'Entrada de Foro (General)',
                'verbose_name_plural': 'Entradas de Foro (Generales)',
            },
        ),
        migrations.CreateModel(
            name='SubTopic',
            fields=[
                ('subtopic_description', models.CharField(max_length=255)),
                ('subtopic_id', models.IntegerField(primary_key=True, serialize=False)),
                ('page_count', models.IntegerField(default=0)),
                ('study_topic_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopics', to='luapol_app.studytopic')),
            ],
        ),
        migrations.AddField(
            model_name='preguntas',
            name='subtema_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luapol_app.subtopic'),
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.CharField(default=luapol_app.models.generate_unique_key, editable=False, max_length=20, primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_submision', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('aciertos', models.IntegerField(default=0)),
                ('aciertos_1', models.IntegerField(default=0)),
                ('tipo', models.CharField(choices=[('PARTIAL', 'Partial'), ('PRACTICE', 'Practice'), ('SIMULATION', 'Simulation'), ('DEFAULT', 'Default')], default='DEFAULT', max_length=20)),
                ('oportunidades', models.IntegerField(default=0)),
                ('aprobado', models.BooleanField(default=False)),
                ('tiempo_medio', models.FloatField(default=0.0)),
                ('usuario_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PreguntaTest',
            fields=[
                ('id', models.CharField(default=luapol_app.models.generate_unique_key, editable=False, max_length=20, primary_key=True, serialize=False)),
                ('es_correcta', models.BooleanField(default=False)),
                ('es_favorita', models.BooleanField(default=False)),
                ('pregunta_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luapol_app.preguntas')),
                ('respuesta_seleccionada_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='luapol_app.respuestas')),
                ('test_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas_test', to='luapol_app.test')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.CharField(default=luapol_app.models.generate_unique_key, editable=False, max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('completado', models.BooleanField(default=False)),
                ('is_review', models.BooleanField(default=False)),
                ('locked', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('user_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('block_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luapol_app.eventsection', to_field='block_number')),
                ('test_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='luapol_app.test')),
            ],
        ),
        migrations.CreateModel(
            name='TestSubtemaFallado',
            fields=[
                ('id', models.CharField(default=luapol_app.models.generate_unique_key, editable=False, max_length=20, primary_key=True, serialize=False)),
                ('fallos', models.IntegerField(default=0)),
                ('subtema_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luapol_app.subtopic')),
                ('test_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luapol_app.test')),
            ],
            options={
                'ordering': ['-fallos'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_given', models.BooleanField(default=False)),
                ('activation_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('user_oto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ForoMeGusta',
            fields=[
                ('id', models.CharField(default=luapol_app.models.generate_unique_key, editable=False, max_length=20, primary_key=True, serialize=False)),
                ('foro_base_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='me_gusta', to='luapol_app.forobase')),
                ('usuario_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('foro_mensaje_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='me_gusta_mensajes', to='luapol_app.foromensajes')),
            ],
            options={
                'unique_together': {('usuario_fk', 'foro_base_fk', 'foro_mensaje_fk')},
            },
        ),
        migrations.CreateModel(
            name='UserAttemptsByDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_attempted', models.DateField(default=django.utils.timezone.now)),
                ('attempt_count', models.PositiveIntegerField(default=1)),
                ('user_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user_fk', 'date_attempted')},
            },
        ),
    ]
