# Generated by Django 5.1.4 on 2025-01-13 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('luapol_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventsection',
            old_name='section_id',
            new_name='block_section_id',
        ),
    ]
