# Generated by Django 5.1.4 on 2025-01-14 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('luapol_app', '0002_rename_section_id_eventsection_block_section_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userattemptsbyday',
            unique_together=set(),
        ),
        migrations.AlterModelTable(
            name='userattemptsbyday',
            table='luapol_app_userattemptsbyday',
        ),
    ]
